### ISSUE TITLE
Shears issues

### ISSUE THREAD

**Issue by tacotexmex** [FaceDeer/vines#2]
- [x] I assume that the shears tool is suppose to enable vine collectiing. Nothing happens when using shears on vines though. The threshold that player has to craft shears is good still, but it needs to work 😃 

- [x] [Add shears sound](https://raw.githubusercontent.com/minetest-games/Minetest_TNG/caec6ad4024f21b112782323c6d19388d98c011e/mods/cme/sheep/sounds/creatures_shears.ogg) (Licensed SmartWentCody(https://freesound.org/people/SmartWentCody) CC-BY 3.0)

- [x] If possible and not stupid, concur the shears with mobs_redo shears so that those mods in combination produces only one item in-game.

**Comment by FaceDeer** [comment]
I've fixed the thing preventing the shears from working. I also made it so that the creatures:shears and mobs:shears will work for cutting down vines, and if either of those mods is installed the vines mod won't allow its own shears to be crafted (though existing shears will still remain in-world).

Haven't done the sound yet, so I won't close this issue just yet. But should be soon.

**Comment by FaceDeer** [comment]
Shear snip sound added.

**Comment by tacotexmex** [comment]
You rock, FaceDeer!
